In [1]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [17]:
import pandas as pd

In [21]:
import pandas as pd

df = pd.read_csv("/content/airbnb_nyc_4819..csv")

print(df.head())

          id                                           name     host_id  \
0  1620248.0  Large furnished 2 bedrooms- - 30 days Minimum   2196224.0
1  3258197.0   Large 1br Duplex in Heart of Upper East Side  16477306.0
2  2459916.0              $455 Cozy 1bd, BKLYN Sublet March  12577771.0
3   375249.0                Enjoy Staten Island Hospitality   1887999.0
4  3359315.0                Sublet near Columbia University  16948705.0

     host_name neighbourhood_group       neighbourhood  latitude  longitude  \
0        Sally           Manhattan        East Village  40.73051  -73.98140
1         Jeff           Manhattan     Upper East Side  40.76866  -73.95553
2       Victor            Brooklyn  Bedford-Stuyvesant  40.68948  -73.93528
3  Rimma & Jim       Staten Island        Graniteville  40.62109  -74.16534
4      Berhani           Manhattan              Harlem  40.81742  -73.95358

         room_type  price  minimum_nights  number_of_reviews last_review  \
0  Entire home/apt   10.0            30.0                0.0   No Review
1  Entire home/apt   16.0             2.0               21.0   6/30/2019
2     Private room   18.0             1.0                0.0   No Review
3     Private room   20.0             3.0               80.0   5/26/2019
4     Private room   22.0            10.0                3.0    8/8/2015

   reviews_per_month  calculated_host_listings_count  availability_365
0               0.00                             4.0             137.0
1               1.69                             1.0               9.0
2               0.00                             1.0               0.0
3               0.92                             1.0             226.0
4               0.05                             1.0               0.0

In [22]:
df['reviews_per_month'].fillna(0, inplace=True)

/tmp/ipykernel_274/1792330394.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['reviews_per_month'].fillna(0, inplace=True)

In [23]:
df = df[df['price'] > 0]

In [24]:
df.groupby("room_type")["price"].mean()

room_type
Entire home/apt    226.743423
Private room        98.450164
Shared room         98.151515
Name: price, dtype: float64

In [25]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.819000e+03,4.819000e+03,4819.000000,4819.000000,4819.000000,4819.000000,4819.000000,4819.000000,4819.000000,4819.000000
mean,1.385204e+06,4.946614e+06,40.728875,-73.961122,176.369786,9.023034,57.685619,0.823642,2.464412,143.788753
std,9.986421e+05,4.542718e+06,0.051128,0.035395,295.875652,28.737986,77.114917,1.063934,6.174551,137.601711
min,2.539000e+03,2.571000e+03,40.508680,-74.239860,10.000000,1.000000,0.000000,0.000000,1.000000,0.000000
25%,5.135155e+05,1.233128e+06,40.688975,-73.984645,82.000000,2.000000,6.000000,0.100000,1.000000,0.000000
50%,1.186153e+06,3.558158e+06,40.723000,-73.960830,125.000000,3.000000,24.000000,0.380000,1.000000,109.000000
75%,2.160244e+06,7.859985e+06,40.762510,-73.945260,195.000000,6.000000,80.000000,1.160000,2.000000,280.000000
max,3.420648e+06,1.856603e+07,40.908040,-73.733230,8000.000000,1000.000000,607.000000,10.000000,52.000000,365.000000

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4819 entries, 0 to 4818
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              4819 non-null   float64
 1   name                            4817 non-null   object
 2   host_id                         4819 non-null   float64
 3   host_name                       4817 non-null   object
 4   neighbourhood_group             4819 non-null   object
 5   neighbourhood                   4819 non-null   object
 6   latitude                        4819 non-null   float64
 7   longitude                       4819 non-null   float64
 8   room_type                       4819 non-null   object
 9   price                           4819 non-null   float64
 10  minimum_nights                  4819 non-null   float64
 11  number_of_reviews               4819 non-null   float64
 12  last_review                     4819 non-null   object
 13  reviews_per_month               4819 non-null   float64
 14  calculated_host_listings_count  4819 non-null   float64
 15  availability_365                4819 non-null   float64
dtypes: float64(10), object(6)
memory usage: 640.0+ KB